# Generated by Django 3.1.5 on 2021-01-27 22:37

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_post', models.CharField(max_length=250, verbose_name='Título')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('conteudo_post', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteudo')),
                ('excerto_post', ckeditor.fields.RichTextField(verbose_name='Excerto')),
                ('imagem_post', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('publicado_post', models.BooleanField(default=False, verbose_name='Publicado')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
